"""LLM-driven self-play prospect (IR5-T4).

The deterministic :class:`~app.simulator.benchmark.RouterProspect` states its target leaf the
moment it's asked, so it can't expose how the agent behaves when a caller is vague, withholds, or
pushes for a price early. :class:`LLMProspect` closes that gap: it drives a persona through the live
chat model using :func:`~app.simulator.personas.persona_system_prompt`, so the prospect hesitates,
gives partial answers, and only names its exact test/subject when the agent earns it — the
weakness-exposing self-play the recursive-improvement loop runs on.

Conversation is role-reversed relative to the agent: the prospect's own lines are ``assistant`` and
the agent's lines are ``user``. ``opening()`` returns the persona's scripted first line (no API
call); each ``next(agent_text)`` feeds the agent's latest reply and returns the prospect's reply.

The OpenAI client is injectable so the unit tests run offline against a stub.
"""

from __future__ import annotations

from app.config import Settings, get_settings
from app.simulator.personas import Persona, persona_system_prompt

# Keep self-play replies short and spoken — the persona prompt already asks for this, but a hard cap
# guards against a chatty model inflating turn counts / token spend.
_MAX_TOKENS = 120


class LLMProspect:
    """A synthetic caller whose turns are generated by the live model from its persona."""

    def __init__(self, persona: Persona, settings: Settings | None = None, *, client=None) -> None:
        self.persona = persona
        self.settings = settings or get_settings()
        self.model = self.settings.openai_chat_model
        self._client = client  # injectable for tests
        # Role-reversed history: the prospect is the "assistant" speaking, the agent is the "user".
        self._messages: list[dict] = [{"role": "system", "content": persona_system_prompt(persona)}]

    @property
    def client(self):
        if self._client is None:
            from openai import OpenAI

            self._client = OpenAI(api_key=self.settings.openai_api_key)
        return self._client

    def opening(self) -> str:
        line = self.persona.opening_line or "Hi, I have a question."
        self._messages.append({"role": "assistant", "content": line})
        return line

    def next(self, agent_text: str = "") -> str:
        """Respond to the agent's latest line, staying in persona."""
        if agent_text:
            self._messages.append({"role": "user", "content": agent_text})
        resp = self.client.chat.completions.create(
            model=self.model, messages=self._messages, max_tokens=_MAX_TOKENS
        )
        reply = (resp.choices[0].message.content or "").strip()
        self._messages.append({"role": "assistant", "content": reply})
        return reply
